---
# https://docs.openstack.org/ocata/install-guide-ubuntu/nova-compute-install.html#

- name: config | Configuring /etc/nova/nova.conf
  template:
    src: "etc/nova/nova.conf.j2"
    dest: "/etc/nova/nova.conf"
    owner: "nova"
    group: "nova"
    mode: "u=rw,g=r,o="
  become: true
  register: "_openstack_compute_service_compute_nova_conf"
  notify: "restart nova-compute"

- meta: flush_handlers
